# ServerUtils Config
language: EN

clearLag: true
clearCooldown: 60
clearLagBroadcast: true

TeleportToSpawnOnJoin: false

alert: false

# HealthIndicator config
showMobHealth: true

# RegionConfig
EnableRegionDisplay: true

# BroadcasterConfig
broadcasterDelay: 3

broadcastBlockBreak:
  IRON_ORE: true
  DIAMOND_ORE: true
  COAL_ORE: true
  GOLD_ORE: true
  LAPIS_ORE: true
  OBSIDIAN: true
  PUMPKIN: true
  GLOWSTONE: true
  EMERALD_ORE: true

broadcastEntityDamage:
  Pig: false
  Sheep: false
  Villager: true
  Enderdragon: true
  Bunny: true
  Bat: true


# DoubleJumpConfig
allowFallDamage: true

doubleJumpUp: 0.5
doubleJumpForward: 1.5